### ISSUE TITLE
Installation fails latest version of pip

### ISSUE THREAD

**Issue by Jakob37** [omar-masmoudi/jupyter-runner#3]
I attempt installation by running:

```
$ pip install jupyter-runner
Collecting jupyter-runner
  Downloading https://files.pythonhosted.org/packages/ba/04/2d2c77714fedd6938d9b072f217fc9354c025ed9c0993e303c83e04be0d2/jupyter_runner-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oayt2fcc/jupyter-runner/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oayt2fcc/jupyter-runner/
```

I run pip version 10.0.1.

```
$ pip --version
pip 10.0.1 from /usr/local/anaconda/lib/python3.6/site-packages/pip (python 3.6)
```

I believe it is related to the following issue:

https://github.com/capless/warrant/issues/96

**Comment by omar-masmoudi** [comment]
Fixed in latest version (0.4.0)
